version: '3.8'

services:
  oracledb:
    image: container-registry.oracle.com/database/express:${DB_ORACLE_VERSION}
    container_name: ${APP_NAME}-oracledb  
    environment:
      ORACLE_CHARACTERSET: ${DB_CHARACTERSET}
      ORACLE_PWD: ${DB_ORACLE_PASSWORD}
    volumes:
      - oracledb:/opt/oracle/oradata
    ports:
      -  ${DB_ORACLE_PORT}:1521
      -  ${DB_MANAGE_PORT}:5500
    restart: always

  apex:
    image: container-registry.oracle.com/database/ords:${APP_VERSION}
    container_name: ${APP_NAME} 
    depends_on:
      - oracledb
    command:
      - /bin/bash
      - -c
      - |
        /bin/echo 'CONN_STRING=sys/$DB_ORACLE_PASSWORD@oracledb:$DB_ORACLE_PORT/xepdb1' > /opt/oracle/variables/conn_string.txt
        sed -i 's/Welcome_1/${APP_PASSWORD}/g' /opt/oracle/apex/setapexadmin.sql
        /bin/bash  /opt/oracle/ords/startService.sh
    ports:
      -  ${APP_PORT}:8181
    restart: always
    
networks:
  default:
      name: ${APP_NAME}

volumes:
  oracledb:

